import { IconType } from "react-icons";

import {
  HiArrowRight,
  HiArrowTopRightOnSquare,
  HiArrowUpRight,
  HiCalendarDays,
  HiEnvelope,
  HiOutlineDocument,
  HiOutlineEye,
  HiOutlineEyeSlash,
  HiOutlineGlobeAsiaAustralia,
  HiOutlineLink,
  HiOutlineRocketLaunch
} from "react-icons/hi2";

import {
  PiBookBookmarkDuotone,
  PiGridFourDuotone,
  PiHouseDuotone,
  PiImageDuotone,
  PiUserCircleDuotone,
} from "react-icons/pi";

import {
  SiAndroidstudio,
  SiC,
  SiCplusplus,
  SiFigma,
  SiFirebase,
  SiGit,
  SiJavascript,
  SiJupyter,
  SiKotlin,
  SiNextdotjs,
  SiPostgresql,
  SiPython,
  SiPytorch,
  SiScikitlearn,
  SiSupabase,
  SiTailwindcss,
  SiTensorflow,
  SiTypescript,
  SiUnity,
  SiVercel,
} from "react-icons/si";

import { FaDiscord, FaFacebook, FaFile, FaGithub, FaInstagram, FaJava, FaLinkedin, FaPinterest, FaReddit, FaTelegram, FaThreads, FaWhatsapp, FaWifi, FaX, FaXTwitter } from "react-icons/fa6";

export const iconLibrary: Record<string, IconType> = {
  arrowUpRight: HiArrowUpRight,
  arrowRight: HiArrowRight,
  email: HiEnvelope,
  globe: HiOutlineGlobeAsiaAustralia,
  person: PiUserCircleDuotone,
  grid: PiGridFourDuotone,
  book: PiBookBookmarkDuotone,
  openLink: HiOutlineLink,
  calendar: HiCalendarDays,
  home: PiHouseDuotone,
  gallery: PiImageDuotone,
  discord: FaDiscord,
  eye: HiOutlineEye,
  eyeOff: HiOutlineEyeSlash,
  github: FaGithub,
  linkedin: FaLinkedin,
  x: FaX,
  twitter: FaXTwitter,
  threads: FaThreads,
  arrowUpRightFromSquare: HiArrowTopRightOnSquare,
  document: HiOutlineDocument,
  rocket: HiOutlineRocketLaunch,
  javascript: SiJavascript,
  nextjs: SiNextdotjs,
  supabase: SiSupabase,
  figma: SiFigma,
  facebook: FaFacebook,
  pinterest: FaPinterest,
  whatsapp: FaWhatsapp,
  reddit: FaReddit,
  telegram: FaTelegram,
  instagram: FaInstagram,
  filepdf: FaFile,
  python: SiPython,
  pytorch: SiPytorch,
  tensorflow: SiTensorflow,
  "scikit-learn": SiScikitlearn,
  typescript: SiTypescript,
  tailwindcss: SiTailwindcss,
  cplusplus: SiCplusplus,
  c: SiC,
  sql: SiPostgresql,
  radio: FaWifi,
  java: FaJava,
  kotlin: SiKotlin,
  "android-studio": SiAndroidstudio,
  firebase : SiFirebase,
  git: SiGit,
  vercel: SiVercel,
  unity: SiUnity,
  jupyter: SiJupyter,
};

export type IconLibrary = typeof iconLibrary;
export type IconName = keyof IconLibrary;
